Create authorization
Teafedos/project_on_ROR pull request #3
Opened 2022-04-26 17:43 UTC by Teafedos

2022-04-28 08:50 UTC, iobitt commented on Gemfile
> +gem 'bcrypt', '~> 3.1.7'
Не обязательно, но хорошо было бы писать комментарий, для чего этот гем нужен в проекте. Так, как это сделано выше

2022-04-28 08:50 UTC, iobitt commented on app/assets/stylesheets/application.css
> +}
лучше создать под регистрацию отдельный файл стилей и вынести эти стили туда

2022-04-28 08:50 UTC, iobitt commented on app/controllers/user_controller.rb
> +  def authorization
Не надо придумывать свои названия методов там, где это не нужно. Это стандартный new. Пусть таким и остаётся

2022-04-28 08:50 UTC, iobitt commented on app/controllers/user_controller.rb
> +  def enter
Для чего нужен этот action? Не нужен - удали. В проекте должен быть только используемый код

2022-04-28 08:50 UTC, iobitt commented on app/controllers/user_controller.rb
> +  def registration
Не нужный метод? (я не вижу, чтобы он что-то делал) Удаляем

2022-04-28 08:50 UTC, iobitt commented on app/controllers/user_controller.rb
> +
Зачем столько пустых строк? Не порядок. Оставляем одну

2022-04-28 08:50 UTC, iobitt commented on app/controllers/user_controller.rb
> +  def datapush
а это стандартный метод create. Так его и называем

2022-04-28 08:50 UTC, iobitt commented on app/controllers/user_controller.rb
> +    if User.exists?(mail: params[:user][:mail]) == false
Используй простую понятную реализацию, как здесь
https://github.com/riskimidiw/rails-jwt/blob/master/app/controllers/users_controller.rb#L17
Но только вызывай render erb шаблонов, а не render json

2022-04-28 08:50 UTC, iobitt commented on app/controllers/user_controller.rb
> +  def testing
Удали, если не используется

2022-04-28 08:50 UTC, iobitt commented on app/controllers/user_controller.rb
> +  def user_params_register
Назови просто user_params. Скорей всего этот набор параметров будет использовать и при создании, и при обновлении

2022-04-28 08:50 UTC, iobitt commented on app/models/user.rb
> +  validates :login, :secretpass, :mail, :nickname, presence: true
Лучше придерживаться стандартных названий, если это какие-то стандартный вещи
mail -> email
secretpass -> password_digest

2022-04-28 08:50 UTC, iobitt commented on app/models/user.rb
> +  validates :nickname, :mail, uniqueness: true
не забудь добавить индекс уникальности на уровне БД (в миграции). Это программные проверки, они могут и не сработать (тема для будущих обсуждений, когда станешь постарше =)

2022-04-28 08:50 UTC, iobitt commented on app/views/user/authorization.html.erb
> +<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous">
Если ты планируешь использовать bootstrap во всём проекте (наверное да), то подключать его нужно в макете layouts

2022-04-28 08:50 UTC, iobitt commented on app/views/user/authorization.html.erb
> +</body>
body и head не нужны (если уберёшь подключение скриптов)

2022-04-28 08:50 UTC, iobitt commented on app/views/user/registration.html.erb
> +<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous">
вот видишь, пошёл дубляж. Подключи в одном месте и не мучайся

2022-04-28 08:50 UTC, iobitt commented on app/views/user/registration.html.erb
> +<%= form_with model: @user, url:datapush_user_index_path,  method: :get do |form| %>
Так вот что делает метод datapush))) (как думаешь, смогут другие разработчики сразу догадаться, что это метод регистрации? Наверное, нет. На самом деле не нужно ничего придумывать. Если создаётся новый user, должен вызываться метод create у user_controller.

Это что, метод get? Не секьюрно. Вообще убери url и method. Рельсы без тебя знают, какой метод использовать и куда слать

2022-04-28 08:50 UTC, iobitt commented on app/views/user/testing.html.erb
> +<%= @test%>
Удаляем этот файл, раз он не используется

2022-04-28 08:50 UTC, iobitt commented on config/initializers/filter_parameter_logging.rb
> -  :passw, :secret, :token, :_key, :crypt, :salt, :certificate, :otp, :ssn
хммм, зачем удаляешь? Это ты сам добавлял?

2022-04-28 08:50 UTC, iobitt commented on config/routes.rb
всё это удаляем, оставляем только
`resources :user`

2022-04-28 08:50 UTC, iobitt commented on config/routes.rb
Кстати, авторизацию выносим в отдельный контроллер. Называем его AuthController. Определяем там метод login. И переносим в этот метод логику авторизации

2022-04-28 08:50 UTC, iobitt commented on db/migrate/20220427124549_create_users.rb
> +      t.string :nickname
https://github.com/iobitt/mysite/blob/master/db/migrate/20220201202635_create_users.rb#L5
Добавляем уникальный индексы на nickname и mail
Желательно, переименовать поля mail и secretpass на стандартные обозначения

2022-04-28 08:50 UTC, iobitt commented on test/controllers/user_controller_test.rb
> -class ClientControllerTest < ActionDispatch::IntegrationTest
полностью удаляем всю папку test. Мы в будущем будет использовать rspec для написания тестов

2022-04-28 09:07 UTC, Teafedos commented on app/controllers/user_controller.rb
> +  def enter
Enter проверяет, есть ли в БД введенные данные, и, если есть, то пускает на основную страницу

2022-04-28 09:10 UTC, Teafedos commented on app/controllers/user_controller.rb
> +  def registration
registration вносит в переменную @user пустую модель, не сохраняя ее и потом загружает страницу registration

2022-04-28 09:12 UTC, Teafedos commented on app/views/user/testing.html.erb
> +<%= @test%>
Он просто для перехода, чтоб было понятно, что авторизация прошла
Сейчас удалю

2022-04-28 09:13 UTC, Teafedos commented on db/migrate/20220427124549_create_users.rb
> +      t.string :nickname
Исправлю

2022-04-28 09:13 UTC, Teafedos commented on test/controllers/user_controller_test.rb
> -class ClientControllerTest < ActionDispatch::IntegrationTest
Удалю

2022-04-28 09:14 UTC, Teafedos commented on config/initializers/filter_parameter_logging.rb
> -  :passw, :secret, :token, :_key, :crypt, :salt, :certificate, :otp, :ssn
Благодаря этим данным, поле password было FILTERED, решил их удалить для решения данной проблемы

2022-04-28 09:15 UTC, Teafedos commented on Gemfile
> +gem 'bcrypt', '~> 3.1.7'
Хорошо, но пока я и сам не знаю как его использовать

2022-04-28 10:39 UTC, Teafedos commented on app/controllers/user_controller.rb
> +  def authorization
Исправил

2022-04-28 20:45 UTC, iobitt commented on Gemfile
> +gem 'bcrypt', '~> 3.1.7'
Он нужен для хранения пароля пользователя в таблице users. Он как раз преобразует пароль в виде текста в хэш сумму

2022-04-28 20:49 UTC, iobitt commented on config/initializers/filter_parameter_logging.rb
> -  :passw, :secret, :token, :_key, :crypt, :salt, :certificate, :otp, :ssn
Мне кажется, не стоит решать проблему таким способом.
Это же тут не просто так было придумано, а чтобы секретные данные не светить. Чтобы они в логи не записывались в чистом вид

2022-04-28 20:50 UTC, iobitt commented on app/controllers/user_controller.rb
> +  def enter
Ну enter это по сути функция логина? Давай всё же вынесем авторизацию в отдельный контроллер. И немного изменим этот метод. Можно будет потом голосом обсудить, как именно он должен работать

2022-04-29 09:13 UTC, Teafedos commented on config/routes.rb
Туда же добавить регистрацию?

2022-04-29 09:13 UTC, Teafedos commented on db/migrate/20220427124549_create_users.rb
> +      t.string :nickname
Исправлено

2022-04-29 09:14 UTC, Teafedos commented on config/initializers/filter_parameter_logging.rb
> -  :passw, :secret, :token, :_key, :crypt, :salt, :certificate, :otp, :ssn
Хорошо, все верну

2022-04-29 09:15 UTC, Teafedos commented on Gemfile
> +gem 'bcrypt', '~> 3.1.7'
Расскажешь тогда голосом как это работает?

2022-04-29 09:15 UTC, Teafedos commented on Gemfile
> +gem 'bcrypt', '~> 3.1.7'
когда созвонимся

2022-04-29 09:16 UTC, Teafedos commented on app/controllers/user_controller.rb
> +  def enter
Туда же добавить регистрацию?

Также нужно будет пересоздать БД или использовать Users?

2022-04-29 10:46 UTC, Teafedos commented on app/assets/stylesheets/application.css
> +}
Сделал

2022-04-29 10:51 UTC, Teafedos commented on config/initializers/filter_parameter_logging.rb
> -  :passw, :secret, :token, :_key, :crypt, :salt, :certificate, :otp, :ssn
Вернул

2022-04-29 10:51 UTC, Teafedos commented on test/controllers/user_controller_test.rb
> -class ClientControllerTest < ActionDispatch::IntegrationTest
Удалил

2022-05-03 08:27 UTC, iobitt commented on Gemfile
> +gem 'bcrypt', '~> 3.1.7'
Я знаю только, что этот гем используется для безопасного хранения паролей. Он пароль в виде текста преобразует в хэш сумму. Строку превратить в хэш просто, а восстановить пароль из хэша достаточно сложно, поэтому это считается более безопасным способом хранить пароли. То есть в бд хранится не пароль, а его отпечаток - хэш)

2022-05-03 08:28 UTC, iobitt commented on Gemfile
> +gem 'bcrypt', '~> 3.1.7'
То есть можешь написать "хэширование паролей". Вообще гем известный, так что можно вообще забить)

2022-05-03 08:30 UTC, iobitt commented on app/controllers/user_controller.rb
> +  def enter
Для регистрации отдельный контроллер AuthController, в котором есть метод register. Пересоздавать БД не нужно, таблицу добавлять тоже нет смысла. Просто используешь модель users в этом контроллере

2022-05-03 08:31 UTC, iobitt commented on app/controllers/user_controller.rb
> +  def registration
Похоже на дикий неоправданный костыль =) Я думаю, можно сделать проще)

2022-05-03 08:32 UTC, iobitt commented on app/assets/stylesheets/auth_css.css
> +}
нужно оставлять пустую строку в конце

2022-05-03 11:39 UTC, slv703 commented on app/assets/stylesheets/user_controller.css
> +}
тут тоже

2022-05-03 11:39 UTC, iobitt commented on app/controllers/user_controller.rb
> +
удалить

2022-05-03 12:24 UTC, iobitt commented on db/migrate/20220428103217_create_users.rb
> +      t.string :password
переименовать password на password_digest

2022-05-08 14:05 UTC, iobitt requested changes

2022-05-08 14:05 UTC, slv703 commented on Gemfile
> +#encode password
Этот гем используется для отладки, а не для безопасного хранения паролей

2022-05-08 14:05 UTC, slv703 commented on Gemfile
> +gem 'bcrypt', '~> 3.1.7'
Если обсуждение по данному вопросу окончено, то тред лучше закрыть, чтобы не мешался =)

2022-05-08 14:05 UTC, slv703 commented on app/assets/stylesheets/auth_controller.css
> +    margin-top: 200px;
Я думаю, это не самый лучший способ расположить форму по центру. Любое другое разрешение экрана и всё поедет. Лучше использовать бутсраповскую сетку хотя бы) Но это тема другого пулл реквеста =)

2022-05-08 14:05 UTC, slv703 commented on app/controllers/auth_controller.rb
> +  end
Я вспомнил, что эта штука делает))) Она не даёт авторизоваться повторно, если ты уже авторизован) Хотя всё равно выглядит как костыль, потому что проверять лучше не session[:user_id], а @current_user. Ну это мой косяк =)

2022-05-08 14:05 UTC, slv703 commented on app/controllers/auth_controller.rb
> +
Тут пустая строчка не нужна)

2022-05-08 14:05 UTC, slv703 commented on app/controllers/auth_controller.rb
> +
Тут тоже пустая строчка лишняя)

2022-05-08 14:05 UTC, slv703 commented on app/controllers/auth_controller.rb
> +  def user_params_register
А вот между private и определением метода строчку стоило бы добавить. Читается лучше)

2022-05-08 14:05 UTC, slv703 commented on app/models/user.rb
> +  validates :password_digest, length: { in: 8..70 }
На password_digest валидацию можно не делать, а вот на password наоборот нужно:
validates :password, length: { minimum: 8 }, if: -> { new_record? || !password.nil? }

PS длина password_digest всегда одинакова, так как это отпечаток

2022-05-08 14:05 UTC, slv703 commented on config/initializers/filter_parameter_logging.rb
> +    :passw, :secret, :token, :_key, :crypt, :salt, :certificate, :otp, :ssn
Два пробела перед этой строчкой лишние) Если бы ты вернул как было, то git бы не показывал изменения строк =)

2022-05-08 14:05 UTC, slv703 commented on db/migrate/20220504110012_create_users.rb
> +      t.string :login
А зачем тебе логин, email и name? Я думаю достаточно оставить либо name и email, а login удалить, раз при входе ты используется email

2022-05-08 14:05 UTC, slv703 commented on db/migrate/20220504110012_create_users.rb
> +      t.string :email
t.string :email, null: false, index: { unique: true }

Это обязательно исправь, чтобы во-первых email всегда был задан, а во-вторых всегда был уникален. Ограничения на уровне БД являются более надёжными и их никак не обойдёшь, в отличи от валидации на уровне модели

2022-05-08 14:05 UTC, iobitt commented on db/migrate/20220504110012_create_users.rb
> +      t.string :name
t.string :name, null: false, index: { unique: true }

Скорей всего имя не должно быть пустым, значит null: false. И раз ты сделал имя уникальным в модели `validates :login, :email, uniqueness: true` тогда сделай его уникальным на уровне базы данных, уникальность на уровне приложения не сказать, что надёжна)

2022-05-08 14:05 UTC, iobitt commented on test/controllers/auth_controller_test.rb
>  require "test_helper"
папка test не нужна, удали

2022-05-08 17:37 UTC, iobitt approved these changes

2022-05-08 17:41 UTC, merged